### ISSUE TITLE
remove links to osmstories.org

### ISSUE THREAD

**Issue by harry-wood** [state-hiu/osmgeoweek-2017#6]
Unfortunately it looks like whoever owned the domain "osmstories.org" has allowed it to lapse and now any links to this site will put money in the pockets of domain squatting spamdexers.

**Comment by d3netxer** [comment]
Thanks for bringing this up, I wasn't aware. This is unfortunate, I never owned the domain, however I have gotten a new domain called osmstories.site and I have it deployed it there.
